### ISSUE TITLE
NPE в методе onError

### ISSUE THREAD

**Issue by RankoR** [KosyanMedia/Aviasales-Android-SDK#14]
```
Fatal Exception: java.lang.NullPointerException
       at ru.aviasales.core.AviasalesSDK$2.onError(SourceFile:282)
       at ru.aviasales.core.search_airports.AirportsDataLoader.onError(SourceFile:28)
       at ru.aviasales.core.http.api.BaseAsyncLoader$1.onFailure(SourceFile:47)
       at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$2.run(ExecutorCallAdapterFactory.java:94)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4514)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
```

Девайс GT-I9300, ОС 4.0.4, портретная ориентация.

**Comment by RankoR** [comment]
Актуально для Template 2.0.10.

**Comment by RankoR** [comment]
Актуально для 2.1.2.
Краш: http://crashes.to/s/a676f747c36

**Comment by oleonov** [comment]
Та же шляпа в отчётах fabric

**Comment by vmelnikov** [comment]
Возникает после вызова AviasalesSDK.getInstance().cancelPlacesSearch(); 
Если сначала набрать несколько символов в строке поиска, а затем удалить их

**Comment by oleonov** [comment]
Комментирование строки  `AviasalesSDK.getInstance().cancelPlacesSearch();` в `SelectAirportFragment.java` в проекте `aviasalestemplate` решает проблему.
232 строка
