### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by RankoR** [KosyanMedia/Aviasales-Android-SDK#15]
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
       at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:223)
       at ru.aviasales.template.ui.model.SearchFormData.<init>(SearchFormData.java:48)
       at ru.aviasales.template.ui.fragment.AviasalesFragment.onCreate(AviasalesFragment.java:43)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
       at android.app.Activity.performStart(Activity.java:6213)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Девайс SM-G531H, ОС 5.1.1, портретная ориентация. SDK 2.0.8

**Comment by RankoR** [comment]
Очень много крашей с этой ошибкой, у 15% пользователей возникает, как выяснилось, на разных устройствах и версиях ОС.

**Comment by oleonov** [comment]
Та же шляпа.

**Comment by Kpeved** [comment]
@RankoR @oleonov  поправили в 2.0.9
