### ISSUE TITLE
IndexOutOfBoundsException when activity is recreated

### ISSUE THREAD

**Issue by bychkovdmitrii** [KosyanMedia/Aviasales-Android-SDK#16]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dbychkov.flights/ru.aviasales.example.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at ru.aviasales.template.ticket.TicketManager.getBestAgencyPrice(TicketManager.java:126)
	at ru.aviasales.template.ui.fragment.TicketDetailsFragment.setupViews(TicketDetailsFragment.java:124)
	at ru.aviasales.template.ui.fragment.TicketDetailsFragment.onCreateView(TicketDetailsFragment.java:68)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1800)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1250)
	at android.app.Activity.performStart(Activity.java:6588)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3112)
	... 10 more

**Comment by Kpeved** [comment]
Seems like this issue from  old version of Aviasales template sdk
