### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by bychkovdmitrii** [KosyanMedia/Aviasales-Android-SDK#17]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dbychkov.flights/ru.aviasales.example.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean ru.aviasales.core.search.object.SearchData.isComplexSearch()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean ru.aviasales.core.search.object.SearchData.isComplexSearch()' on a null object reference
	at ru.aviasales.template.ui.fragment.ResultsFragment.createOrRefreshAdapter(ResultsFragment.java:117)
	at ru.aviasales.template.ui.fragment.ResultsFragment.setUpListView(ResultsFragment.java:97)
	at ru.aviasales.template.ui.fragment.ResultsFragment.setUpViews(ResultsFragment.java:88)
	at ru.aviasales.template.ui.fragment.ResultsFragment.onCreateView(ResultsFragment.java:69)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2042)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1976)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2042)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:6036)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
	... 10 more

**Comment by Kpeved** [comment]
@bychkovdmitrii Could you please add more details about this crash? When this exception is thrown ?

**Comment by RankoR** [comment]
Та же проблема с последней версией Template Project:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.futuregaming.aviasales.one/com.futuregaming.aviasales.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2996)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3025)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
       at android.app.ActivityThread.access$900(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at ru.aviasales.template.ui.fragment.ResultsFragment.createOrRefreshAdapter(ResultsFragment.java:143)
       at ru.aviasales.template.ui.fragment.ResultsFragment.setUpListView(ResultsFragment.java:104)
       at ru.aviasales.template.ui.fragment.ResultsFragment.setUpViews(ResultsFragment.java:95)
       at ru.aviasales.template.ui.fragment.ResultsFragment.onCreateView(ResultsFragment.java:75)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2133)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1151)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2159)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:507)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:496)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at android.app.Activity.performResume(Activity.java:5414)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3025)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
       at android.app.ActivityThread.access$900(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Когда крашится — сказать не могу, крашится у юзеров. Присутствует на Android 4, 5, 6. Сегодня у нас затронуло 10 юзеров из 800.
