### ISSUE TITLE
ru.aviasales.template:aviasalesSdkTemplate:2.1.7 minSDK >= 11

### ISSUE THREAD

**Issue by Sergey-NT** [KosyanMedia/Aviasales-Android-SDK#35]
Template used method progressbar.setAlpha(). setAlpha() was introduced in API11.
 
STACK_TRACE = java.lang.NoSuchMethodError: android.widget.ProgressBar.setAlpha
	at ru.aviasales.template.ui.fragment.BrowserFragment.setupViews(BrowserFragment.java:94)
	at ru.aviasales.template.ui.fragment.BrowserFragment.onCreateView(BrowserFragment.java:83)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1155)
	at android.app.Activity.performStart(Activity.java:3951)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1662)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:118)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:948)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3773)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:529)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
	at dalvik.system.NativeStart.main(Native Method)

You could be getting this error because you are supporting too low of an API for this method. Since it doesn't exist at an API < 11 the compiler will throw a NoSuchMethodError exception.

**Comment by Kpeved** [comment]
@Sergey-NT We don't use BrowserFragment on api < 19 . There should be set annotation @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH) . SDK should work on api 9. 
Did you change something else in project ?
