### ISSUE TITLE
%d can't format java.lang.String arguments

### ISSUE THREAD

**Issue by RankoR** [KosyanMedia/Aviasales-Android-SDK#36]
Последняя версия Template.

> Fatal Exception: java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments
>        at java.util.Formatter.badArgumentType(Formatter.java:1489)
>        at java.util.Formatter.transformFromInteger(Formatter.java:1689)
>        at java.util.Formatter.transform(Formatter.java:1461)
>        at java.util.Formatter.doFormat(Formatter.java:1081)
>        at java.util.Formatter.format(Formatter.java:1042)
>        at java.util.Formatter.format(Formatter.java:1011)
>        at java.lang.String.format(String.java:1803)
>        at android.content.res.Resources.getString(Resources.java:668)
>        at android.content.Context.getString(Context.java:390)
>        at android.widget.SimpleMonthView$MonthViewTouchHelper.getItemDescription(SimpleMonthView.java:683)
>        at android.widget.SimpleMonthView$MonthViewTouchHelper.onPopulateNodeForVirtualView(SimpleMonthView.java:627)
>        at com.android.internal.widget.ExploreByTouchHelper.createNodeForChild(ExploreByTouchHelper.java:397)
>        at com.android.internal.widget.ExploreByTouchHelper.createNode(ExploreByTouchHelper.java:324)
>        at com.android.internal.widget.ExploreByTouchHelper.access$100(ExploreByTouchHelper.java:49)
>        at com.android.internal.widget.ExploreByTouchHelper$ExploreByTouchNodeProvider.createAccessibilityNodeInfo(ExploreByTouchHelper.java:741)
>        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:805)
>        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:155)
>        at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:53)
>        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1146)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:135)
>        at android.app.ActivityThread.main(ActivityThread.java:5910)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

Подробностей больше нет, краш из крашлитикса.

**Comment by Kpeved** [comment]
@RankoR Спасибо за отчет . Судя по всему краш из андроидовского пикера даты. По этому логу сказать что и где упало сейчас не возможно  (

**Comment by RankoR** [comment]
@Kpeved https://stackoverflow.com/questions/28618405/datepicker-crashes-on-my-device-when-clicked-with-personal-app — собственно, вот :)
