### ISSUE TITLE
NPE в CoreDefined

### ISSUE THREAD

**Issue by RankoR** [KosyanMedia/Aviasales-Android-SDK#37]
```
Fatal Exception: java.lang.NullPointerException
       at ru.aviasales.core.utils.CoreDefined.isAviasales(SourceFile:99)
       at ru.aviasales.core.search_airports.AirportsDataLoader.createCall(SourceFile:38)
       at ru.aviasales.core.http.api.BaseAsyncLoader.load(SourceFile:27)
       at ru.aviasales.core.AviasalesSDK.startPlacesSearch(SourceFile:287)
       at ru.aviasales.template.ui.fragment.SelectAirportFragment$8.run(SelectAirportFragment.java:251)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by Kpeved** [comment]
@RankoR  Много ли таких крашей? Повторяется ли на последней версии?

**Comment by RankoR** [comment]
@Kpeved таких не очень много. На последней не тестировали.
