### ISSUE TITLE
StringIndexOutOfBoundsException when AviasalesSDK.getInstance()

### ISSUE THREAD

**Issue by FitrahRama** [KosyanMedia/Aviasales-Android-SDK#74]
I use SDK version 2.1.16 :

```
implementation 'ru.aviasales:aviasalesSdk:2.1.16-sdk'
implementation 'ru.aviasales.template:aviasalesSdkTemplate:2.1.16'
```

When I do `AviasalesSDK.getInstance().init(this, SdkConfig(TRAVEL_PAYOUTS_MARKER, TRAVEL_PAYOUTS_TOKEN, SDK_HOST))` in my Activity before setContentView, this crash happened. 
Log :
> ```
> StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=2
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>         at android.app.ActivityThread.-wrap11(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.app.ActivityThread.main(ActivityThread.java:5417)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>      Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=2
>         at java.lang.String.startEndAndLength(String.java:298)
>         at java.lang.String.substring(String.java:1087)
>         at ru.aviasales.core.locale.LocaleUtil.a(SourceFile:131)
>         at ru.aviasales.core.locale.LocaleUtil.getLocale(SourceFile:48)
>         at ru.aviasales.core.locale.LocaleUtil.getSdkHost(SourceFile:342)
>         at ru.aviasales.core.utils.CoreDefined.getHost(SourceFile:73)
>         at ru.aviasales.core.search.DeviceInfoHeaderBuilder.getDeviceInfo(SourceFile:47)
>         at ru.aviasales.core.installtracking.InstallTrackingApi.getService(SourceFile:19)
>         at ru.aviasales.core.installtracking.InstallLoader.createCall(SourceFile:24)
>         at ru.aviasales.core.http.api.BaseAsyncLoader.load(SourceFile:28)
>         at ru.aviasales.core.installtracking.InstallInitializer.initFirstLaunch(SourceFile:30)
>         at ru.aviasales.core.AviasalesSDK.init(SourceFile:97)
> ```

**Comment by Kpeved** [comment]
Hi @FitrahRama .
Do you still experience this problem?

**Comment by FitrahRama** [comment]
Hi, @Kpeved.
Yes, I still experience this problem.

**Comment by Kpeved** [comment]
Do you use our template (simple_demo, navdrawer_demo) or your own  project?

**Comment by Kpeved** [comment]
@FitrahRama 
Can you please provide the following information:
- Do you use our template (simple_demo, navdrawer_demo) or your own project?
-  Language of the phone, device model.
